### ISSUE TITLE
Creating a new page: should add localization

### ISSUE THREAD

**Issue by nicolasmol** [rashadAdel/getx-helper#2]
Actually:
![image](https://user-images.githubusercontent.com/61077647/190275322-74fdc50f-2655-4dac-b3a2-b593cff210af.png)
I guess should better be...
![image](https://user-images.githubusercontent.com/61077647/190275402-a86da13d-1194-4b5c-bb80-0fcd58ad32a2.png)

**Comment by rashadAdel** [comment]
done
