### ISSUE TITLE
Router improvement suggestion

### ISSUE THREAD

**Issue by nicolasmol** [rashadAdel/getx-helper#4]
You should combine Pages & Routes in a single file `app_router` and use of _WidgetPage.routename_.
Because it simplifies code navigation 
![image](https://user-images.githubusercontent.com/61077647/191975148-78566dc8-88cf-4f45-83d7-d339c4af454a.png)
![image](https://user-images.githubusercontent.com/61077647/191975528-8056ac9c-484b-4e7a-8b4d-29bb9fa61b22.png)

**Comment by rashadAdel** [comment]
thanks for your suggest 
i did it
